import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import globals from "globals";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

// Only the Next.js half of the repo gets React, JSX and TypeScript rules.
// `server/` and `scripts/` are plain Node and are configured further down, so
// they are not measured against hooks or a11y rules they cannot satisfy.
const nextFiles = [
  "app/**/*.{ts,tsx}",
  "middleware.ts",
  "next.config.ts",
  "vitest.config.ts",
];

export default [
  {
    ignores: [
      ".next/",
      // next.config.ts honours NEXT_DIST_DIR so a production build can run
      // beside a dev server; those builds land in .next-<something>.
      ".next-*/",
      "coverage/",
      "next-env.d.ts", // generated by Next
      "**/*.tsbuildinfo",
    ],
  },

  js.configs.recommended,

  // eslint-config-next is still eslintrc-format, so FlatCompat translates it.
  // Pinning `files` on each translated block is what keeps it off the Node code.
  ...compat
    .extends("next/core-web-vitals", "next/typescript")
    .map((config) => ({ ...config, files: nextFiles })),

  // Realtime Socket.IO server: CommonJS, Node globals only.
  {
    files: ["server/src/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: globals.node,
    },
  },

  // Migration/inspection scripts and the ESM config files: Node ESM.
  {
    files: ["scripts/**/*.mjs", "*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: globals.node,
    },
  },
];
